vich_uploader:
    db_driver: orm

    mappings:
        user_picture:
            uri_prefix: /upload/user
            upload_destination: '%kernel.project_dir%/public/upload/user'
       #     namer:
       #         service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        article_picture:
            uri_prefix: /upload/media
            upload_destination: '%kernel.project_dir%/public/upload/media'
            #     namer:
            #         service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
