vich_uploader:
    db_driver: orm

    mappings:
        user_picture:
            uri_prefix: /upload/user
            upload_destination: '%kernel.project_dir%/public/upload/user'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        article_picture:
            uri_prefix: /upload/media
            upload_destination: '%kernel.project_dir%/public/upload/media'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        media_picture:
            uri_prefix: /upload/galerie
            upload_destination: '%kernel.project_dir%/public/upload/galerie'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        encadrement_picture:
            uri_prefix: /upload/media
            upload_destination: '%kernel.project_dir%/public/upload/media'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        avatar_galerie_picture:
            uri_prefix: /upload/galerie
            upload_destination: '%kernel.project_dir%/public/upload/galerie'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        document_picture:
            uri_prefix: /upload/document
            upload_destination: '%kernel.project_dir%/public/upload/document'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        vikaEvent_picture:
            uri_prefix: /upload/vikaEvent
            upload_destination: '%kernel.project_dir%/public/upload/vikaevent'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        sponsors_picture:
            uri_prefix: /upload/media
            upload_destination: '%kernel.project_dir%/public/upload/media'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
