parameters:

  onurb_yuml.colors:
    App\Entity\User: mediumspringgreen
    App\Entity\Registration: mediumspringgreen
    App\Entity\Article: mediumspringgreen
    App\Entity\Gallery: mediumspringgreen
    App\Entity\VikaEvent: mediumspringgreen
    App\Entity\UserConnected : yellow
    
    
  onurb_yuml.extension: svg
  onurb_yuml.scale: tiny